### ISSUE TITLE
验证集上的 context 参数在哪里设置？

### ISSUE THREAD

**Issue by gzhcv** [THUNLP-MT/Document-Transformer#1]
论文中提到模型的训练分两步：
1. 先用全部训练集（包括句子级和文档级的平行句对）训一个transformer模型。
2. 固定第一步transformer模型的参数，用文档级的平行句对单独训context input模块的参数。

我在做第2步的时候有两个疑问：
1)  trainer_ctx.py 中的参数 --input 包括source和target语料 --context参数论文中说用target端的语料效果好些。在这套代码里设置为source端的语料也是可以的吧？另外，这个context语料是不是和input参数中的source或target语料是一样的？

2) 在训练contextual_transformer模型期间，我想看验证集上的效果，验证集的context参数如何指定呢？

**Comment by Glaceon31** [comment]
1. 论文中的context是使用的source端的文档上文。我刚刚更新了readme，在FAQ中说明了context语料应该如何得到，可以参考一下。

2. 验证集的context和训练时候同理，都是使用的source端的文档上文。因为我暂时还没有加入训练时做验证的代码。建议先保存模型后使用translator_ctx.py进行翻译来验证。

**Comment by gzhcv** [comment]
清楚了哈~  非常感谢~~
