### ISSUE TITLE
loss为负数

### ISSUE THREAD

**Issue by kFoodie** [THUNLP-MT/Document-Transformer#4]
你好，按照readme的流程，我进行了如下操作：

1. 利用句子级平行语料及文档级平行语料训练得到了基本的transformer模型；这里我使用的是之前训练好的t2t里面的transformer。
2. 使用文档级平行语料训练一个虚拟的context_transformer模型；
3. 将第一步得到的基本transformer模型merge到第二步的虚拟模型中，以初始化context模型；
4. 训练context模型。

其中2,3,4步我都只使用了文档级平行语料。第1步的词表有经过bpe，第2，3，4步的词表相同，都是使用了bpe。
另外，thumt/data/datasey.py 在 python2 中报了错。
```
params.mapping["target"][params.unk]
```
报了一个KeyError的错，我直接改成
```
default_value=-1
```

所以我不太确定是因为词表不同，导致 loss 出现负数；还是因为我改了代码导致的。

另外，我想请教一下，default_value 怎么修改比较好。

为了方便作者可以定位我的错误，现我把具体的训练脚本也附上：
```
python2 thumt/bin/trainer_ctx.py \
--input corpus/train.en corpus/train.zh \
--context corpus/train.ctx.en \
--vocabulary vocab/vocab.en vocab/vocab.zh \
--output models/dummy \
--model contextual_transformer \
--parameters train_steps=1

python2 thumt/scripts/combine_add.py \
--model models/dummy \
--part models/transformer/model.ckpt-300000 \
--output models/train/

python2 thumt/bin/trainer_ctx.py \
--input corpus/train.en corpus/train.zh \
--context corpus/train.ctx.en \
--output models/sentence_doc \
--vocabulary vocab/vocab.en vocab/vocab.zh \
--model contextual_transformer \
--parameters start_steps=95000,num_context_layers=1,batch_size=6250,train_steps=100000,save_checkpoint_steps=5000,keep_checkpoint_max=50,beam_size=5
```

跪求大神可以看到我的留言，帮忙看一下是否我哪里的操作不当导致训练过程出错，万分感谢！

**Comment by Glaceon31** [comment]
可能是词表不同导致的，第2、3、4步使用的词表和第一步的词表也必须一致。通过调整词表和对应的参数应该是可以做到的。

建议先尝试使用t2t训练的模型、我们的代码（不含context部分）能够正常进行解码之后再尝试context训练

**Comment by kFoodie** [comment]
好哒，谢谢大神~
