### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by abhranil08** [THUNLP-MT/Document-Transformer#5]
How do I get the dataset, as you mentioned for training the dummy improved transformer model? and then how do I make the context corpus? Will it be a data with multiple documents, converted to sentence1,sentence2....sentence n of each document with a delimiter?

**Comment by Glaceon31** [comment]
Step 2 does not mean to train the model, it is only used to initialize an (dummy) improved transformer model. 

Please refer to the FAQ part in README.md which gives a detailed example of making the context corpus.

**Comment by abhranil08** [comment]
how will the source corpus and target corpus exactly be, when feeding it to your system? how will two different documents be separated? The initial dataset will be a source corpus with document1,document2...document n and the same with the target corpus. 

==== train.src ==== (source corpus)
source sentence #1( Document#1)
source sentence #2 ( Document#1)
source sentence #3 ( Document#1)
source sentence #4 ( Document#1)
source sentence #1( Document#2)
source sentence #2 ( Document#2)
source sentence #3 ( Document#2)
source sentence #4 ( Document#2)
source sentence #1( Document#3)
source sentence #2 ( Document#3
source sentence #3 ( Document#3)
source sentence #4 ( Document#3)

Then the source corpus feeding to your system will be like this? and the same for the target corpus?

**Comment by Glaceon31** [comment]
Yes, the source and target corpus will be like this, and the context corpus will be like:

==== train.ctx ==== (context corpus)

source sentence #1 ( Document#1)
source sentence #1 source sentence #2 ( Document#1)
source sentence #2 source sentence #3 ( Document#1)

source sentence #1 ( Document#2)
source sentence #1 source sentence #2 ( Document#2)
source sentence #2 source sentence #3 ( Document#2)

source sentence #1 ( Document#3)
source sentence #1 source sentence #2 ( Document#3)
source sentence #2 source sentence #3 ( Document#3)
