### ISSUE TITLE
Is this available in python 3 version?

### ISSUE THREAD

**Issue by riktimmondal** [THUNLP-MT/Document-Transformer#6]
Since I don't have all the deep learning and other libraries not installed in python 2 I can't it.
I also tried to run it on Google colab using python 2 kernal but there I am not able to add the path of THUMT folder to the python path.
Can you suggest some remedy to it?

Thanks a lot.

**Comment by Glaceon31** [comment]
Sorry that we do not support python 3 for the time being.

If you cannot add the path of THUMT folder to the python path, you can attempt to add a temporary python path by appending `PYTHONPATH=\path\to\THUMT` to the start of the bash command when running the code.

**Comment by riktimmondal** [comment]
Thanks for replying I will solved the issue
