### ISSUE TITLE
Optimal training parameters

### ISSUE THREAD

**Issue by barbara3430** [THUNLP-MT/Document-Transformer#8]
Hello,
I am training your model on a combination on IWSLT, Europarl and News Commentary French, Russian and German data. Do you have any tips on what should be the optimal training configuration parameters outside of what is already contained in the README?

Thanks!
Barbara

**Comment by Glaceon31** [comment]
Sorry for the late. You may use the default setting as there is nothing special to change. Make sure you set the start_steps correct!
