### ISSUE TITLE
关于IWSLT Fr-EN的参数设置

### ISSUE THREAD

**Issue by scewiner** [THUNLP-MT/Document-Transformer#9]
您好，
       我对你们这篇工作非常感兴趣，最近在复现这篇工作在iwslt, fr-en上的结果，但是遇到了一些问题，SAN-base model,  我跑的是34.89, 单句context, 两句context是35.55，35.57， 和paper report的结果相差有点远。
所以想跟您确认以下参数，这是我的设置：
    1. share_target_embedding_and_softmax=true, 是否要开呢?
    2. attention_dorpout=0.15,relu_dropuout=0.1, residual_dropout=0.1；还是使用默认的设置？
    3. learning_rate=1.0，warmup_step=8000, 
    此外
    layer_norm需要改成 preprocess吗？
    第二步中：
    1. learning_rate调1.0，还是0.1有什么区别吗？ 我看combin_add的脚本好像也读取了adam的参数，应该是属于继续训练的吧，那lr应该是跟着pre-train model的？而且30000 step也远超warmup_step，属于下降区间中，我觉得应该不会有影响才是。 但是我的结果，lr=1 比lr=0.1要好一些。
   2. 因为没有eval的结果做参考，模型改怎么挑选呢？
       save_checkpint_steps=1000, 这个你们设置是多少呢？感觉很容易错过模型

期待您的回复
谢谢

**Comment by Glaceon31** [comment]
您好，34.89、35.57和我们论文里报的结果（35.15、36.04）差的不是很远了。参数确实有不一样的地方，我们的参数使用的都是这个repository里的默认参数，没有经过很仔细的调整，调整后是可能取得更好的效果的。

learning_rate调0.1指的是在第二步训练文档级别对应模块的时候的学习率，第一步训练标准Transformer模型的时候的学习率还是1.0。combine_add虽然读了adam参数，但是因为第二步训练的时候把第一步训的参数都锁死了，所以其实并没有继续训练。那个30000是start_steps不是warmup_step，只是为了初始化第二步训练的学习率衰减，实际使用中要设置成第一步训练的模型所对应的学习轮数。eval方面，我们也是save_checkpint_steps=1000，然后在开发集上做解码测BLEU来找到最好的模型。

**Comment by scewiner** [comment]
感谢您的回复，我这边跑了一个default的结果，baseline只有33.2分，batch_size和paper一样2w4，
> python ../thumt/bin/trainer.py \
    --input $data/train.bpe.fr $data/train.bpe.en\
    --vocabulary $data/vocab.fr.txt $data/vocab.en.txt\
    --validation $data/dev2010.bpe.fr \
    --reference $data/dev2010.bpe.en \
    --model transformer \
    --parameters batch_size=12000,update_cycle=2,,device_list=[0],train_steps=32000 

这是我的脚本，加了shared_embedding_and_softmax_weights=True之后，我跑的baseline是35,6，one sentence context也可以达到36.2，但是two sentence的才35.8, 我不清楚是不是处理数据的问题，我想请问以下几个问题：
   1. ctx数据，只有第一行是空的吗？ 还是每个篇章的第一行都是空的？
   2. 关于BPE，是joined-bpe还是分别做的bpe？
方便的话，可以提供数据处理的脚本吗？

期待您的回复，
谢谢

**Comment by Glaceon31** [comment]
有可能是数据处理的问题。

我们的处理方法是先使用我们内部的一个脚本做标准化，然后按顺序使用moses中的tokenizer和lowercase脚本，测BLEU也是case-insensitive的。BPE我们是分别做的。您可以提供一个邮箱，我可以将我们使用的标准化脚本发给您。

ctx数据是每一个篇章的第一行都是空的。另外您也可以给我发一下第二步训练时使用的命令

**Comment by scewiner** [comment]
谢谢，我的邮箱是yb77460@umac.mo
这是我第二步的脚本：
> python ../thumt/bin/trainer_ctx.py \
    --input $data/train.bpe.fr $data/train.bpe.en\
    --context /home/ma-user/work/iwslt-fren/ctx/train.2sent.fr \
    --vocabulary $data/vocab.fr.txt $data/vocab.en.txt\
    --model contextual_transformer \
    --output train \
    --checkpoint ../base/train/eval/model.ckpt-6000 \
    --parameters batch_size=12000,update_cycle=2,device_list=[0],shared_embedding_and_softmax_weights=True,num_context_layers=1,train_steps=50000

我也尝试了分开做BPE的，但是baseline的效果会降低一些

**Comment by Glaceon31** [comment]
看上去训练脚本没啥问题，标准化脚本已发邮箱~

**Comment by yangkexin** [comment]
您好，我最近也在复现这个工作，数据标准化脚本如果可以，能麻烦也发一下吗~邮箱是279413227@qq.com

**Comment by Glaceon31** [comment]
已发！

**Comment by cairouchong** [comment]
处理数据时有些问题，想参考一下数据标准化脚本，如果可以的话能麻烦发一下吗？邮箱是4319cxy@sina.com，十分感谢

**Comment by Glaceon31** [comment]
@cairouchong 已发送
